web:
    image: hitalos/laravel:latest
    container_name: teste_pratico
    ports:
        - 8577:80
    volumes:
        - ./:/var/www
    #links:
     #   - db
    stdin_open: true
    tty: true
db:
  image: postgres
  container_name: postgres2
  #restart: always
  ports:
    - 5433:5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: senha
    POSTGRES_DB: TestePratico